### ISSUE TITLE
Question: Where the hell is Godot 4.3? It doesn't even come up in Google.

### ISSUE THREAD

**Issue by BurntAussieTyre** [aaronfranke/godot-gltf-khr-xmp-copyright#1]

**Comment by aaronfranke** [comment]
This addon can only be used with a Godot version from the future.

Ok but seriously: This addon requires a pull request which has not been merged yet, but will be merged for 4.3. I posted a link to this pull request in the README file.

**Comment by aaronfranke** [comment]
The [pull request I mentioned](https://github.com/godotengine/godot/pull/79316) has been merged, so this repo can be used with the latest master branch of Godot.
